### PR TITLE
Implement call recording

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Solves https://github.com/GrapheneOS/os-issue-tracker/issues/868

**Comment by Amolith** [comment]
Any ETA on getting this merged? I'm a small business owner and would love to have this feature natively rather than through a crappy third-party app.

**Comment by thestinger** [comment]
No, it's very complex and looks like it would be very difficult to port to new versions of Android. It would be near guaranteed to be dropped as part of migrating to Android 13 and each subsequent version. It's not possible to maintain something like this for an AOSP component in a reason way. It will likely be closed for that reason.

**Comment by thestinger** [comment]
If you're willing to provide $10000/year to pay someone specifically to port this feature to each new Android version in an extremely time sensitive way it could be merged.

**Comment by thestinger** [comment]
If you're willing to provide something like $5000/year to pay someone specifically to port this feature to each new Android version (potentially more than once per year) in an extremely time sensitive way it could be merged. As is, I don't see how we can merge this. It would take away substantial time from porting what we already have to each new Android release. I don't see how we can ship this.

**Comment by thestinger** [comment]
I've archived this pull request at https://github.com/GrapheneOS/platform_packages_apps_Dialer/tree/call-recording. My intention wasn't to reject it but to express that I'm pessimistic about it because it looks like it would be difficult to maintain. It would need to be ported forward to each new release of Dialer which can have substantial changes released as part of a new major release of Android. If this was a standalone app not from AOSP, it would be different, but we would need resources specifically to maintain stuff like this. I'm already getting worried about the amount of changes we've added since the release of Android 12.

**Comment by thestinger** [comment]
https://github.com/GrapheneOS/platform_packages_apps_Dialer/pull/12

**Comment by poiNt3D** [comment]
Maybe the best way to do this is not include it into the dialer app, but to decouple it to a separate app. Or just to make an option to allow third party apps to do it.
This is a really needed and requested feature.

**Comment by thestinger** [comment]
Asking for it won't make it happen faster.

**Pull request closed without merging**
