### PR TITLE
Implement call recording

### PR DESCRIPTION
**Pull request by thestinger**
Signed-off-by: June <june@eridan.me>
Co-authored-by: June <june@eridan.me>
Co-authored-by: Danny Baumann <dannybaumann@web.de>

### CODE REVIEW

**Comment by lbdroid** [comment]
Whats the status on this?

**Comment by ghost** [comment]
It's too much code for an AOSP project that is actively maintained so conflicts and issues will arise easily and maintenance will be extremely difficult. The way this is done is not getting merged.

A different implementation needs to be done that has less code.

**Comment by ghost** [comment]
It was a mistake publicising this because too many people are constantly bumping, pinging, and even emailing my personal and work emails about the status of call recording when it's actually a very bad implementation that has too much code and is incredibly difficult to maintain long term and I have serious concerns with database upgrading/downgrading with backups.

**Comment by PatrykMis** [comment]
https://github.com/chenxiaolong/BCR looks good. May be it will be possible to include it or some kind of stub/shim  to install it and then make it work?
I don't think it makes sense to compile whole system for my phones just to be able to record calls, especially when it is not only request made by me. There is also [this thread on GrapheneOS forums](https://discuss.grapheneos.org/d/111-status-of-call-recording), posts on Twitter etc. As you can see there is really much interest of implementing call recording especially if GrapheneOS (hopefully) does not support rooting.

**Comment by ghost** [comment]
Not poking security holes into the base OS for call recording.

**Comment by ghost** [comment]
@thestinger Please delete this PR.

**Comment by PatrykMis** [comment]
@Zanthed  Daniel Micay has to delete this PR only because call recording is not important for someone like e.g. you?

If we would go that way, the sandboxed Google compatibility layer wouldn't probably be ever developed and included because Google is not trustworthy, because GSF/GMS is closed-source and so on...

Let's make some kind of compromise. BCR or this PR doesn't have to be included, but let's make it as an option, like for GSF/GMS/Play Store. They're not installed by default but they work if someone consciously install them.

**Comment by ghost** [comment]
Read https://discuss.grapheneos.org/d/111-status-of-call-recording/11

**Comment by ghost** [comment]
I'm not going to repeat what I've stated about call recording. I'll copy and paste exactly what needs to be said and no discussion needs to be had.

It's too much code for an AOSP project that is actively maintained so conflicts and issues will arise easily and maintenance will be extremely difficult. The way this is done is not getting merged.

A different implementation needs to be done that has less code.
It was a serious mistake publicising this because too many people are constantly bumping, pinging, and even emailing my personal and work emails about the status of call recording when it's actually a very bad implementation that has too much code and is incredibly difficult to maintain long term and I have serious concerns with database upgrading/downgrading with backups.

If you want call recording so badly, then I suggest you start investing your own time and effort and research and development and maybe even paying someone to make a far better implementation that can be submitted to either upstream AOSP or to us and is willing to make any changes that we request.

We're not contract workers, we're not accepting bounties, we're not doing something just because you keep on pinging us about it.

**Comment by PatrykMis** [comment]
Anyway, it doesn't reply to proposal of including the way to successfully use BCR or other similar software (if it exists). It could be simple switch in settings -> security to allow GRANTING CAPTURE_AUDIO_OUTPUT permission to this kind of software. Native code debugging or exec spawning are switches too.

**Pull request closed without merging**
